name: Build & Push image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # ↓ Owner in Kleinbuchstaben in GITHUB_ENV schreiben
      - name: Set image owner (lower-case)
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/rvc-cli-docker:latest
            ghcr.io/${{ env.IMAGE_OWNER }}/rvc-cli-docker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
